extern	void	CHROUT	(char d);
extern	char	CHRIN	();
extern	void	PRNTLN	(const char * s);
extern	void	PRNT	(const char * s);
extern	void	PRNL	();
extern	void	SETBNK	(char d);
extern	char	GETBNK	();
extern	void	SNINIT	();
extern	void	SNWRT	(char d);
extern	void	SHDLY	();
extern	void	RST	();
extern	char	KBINPUT	();
extern	char	KBGET	();
extern	char	KBSCAN	();
extern	void	KBINIT	();
extern	char	INPUT	();
extern	void	DLY	();
extern	void	INTE	();
extern	void	INTD	();
extern	void	GET_INT	();
extern	char	ACIA_SCAN	();
extern	void	SPI_INIT	();
extern	void	SPI_WRITE	(char d);
extern	void	GD_INIT	();
extern	void	GD_CHROUT	(char d);
extern	void	GD_WRITE8	(unsigned int addr, char v);
extern	void	GD_CLR	();
extern	void	GD_WRITE16	(unsigned int addr, unsigned int v);
extern	void	GD_SET_CUR	(char x, char y);
