extern	void	CHROUT	(char d);
extern	char	CHRIN	();
extern	void	PRNTLN	(const char * s);
extern	void	PRNT	(const char * s);
extern	void	PRNL	();
extern	void	SETBNK	(char d);
extern	char	GETBNK	();
extern	void	SNINIT	();
extern	void	SNWRT	(char d);
extern	void	SHDLY	();
extern	void	RST	();
extern	char	KBINPUT	();
extern	char	KBGET	();
extern	char	KBSCAN	();
extern	void	KBINIT	();
extern	char	INPUT	();
extern	void	DLY	();
extern	void	INTEN	();
extern	void	INTDI	();
extern	void	GET_INTERRUPT	();
extern	char	ACIA_SCAN	();
extern	void	SPI_INIT	();
extern	void	SPI_WRITE	(char d);
extern	void	GDINIT	();
extern	void	GD_CHROUT	(char d);
extern	void	GD_WRITE8	(unsigned addr, char v);
extern	void	GD_CLR	();
extern	void	GD_WRITE16	(unsigned addr, unsigned v);
extern	void	GD_CUR_SET	(char x, char y);
extern	char	ACIA_IN	();
extern	void	ACIAINIT	();
extern	void	GD_CLR_TXT	();
extern	void	GD_BCK	();
