const char * m0 = "APPARTUS PROJEKT65 v9-1-3 Bootloader v7";
const char * m1 = "w for start write to RAM";
const char * m2 = "m for start monitor";
const char * m3 = "ACIA ";
const char * m4 = "PS2 ";
const char * m5 = "VDP ";
const char * m6 = "Initialised";
const char * m7 = "not Found!";
const char * m8 = "ERROR!";
